enum NetworkError {
  DNS_LOOKUP_ERROR = 'ENOTFOUND',
  CONNECTION_RESET = 'ECONNRESET',
  CONNECTION_TIMEOUT = 'ETIMEDOUT',
  RESPONSE_TO_LONG = 'ESOCKETTIMEDOUT',
}

export const RETRIABLE_ERRORS = [
  NetworkError.DNS_LOOKUP_ERROR,
  NetworkError.CONNECTION_RESET,
  NetworkError.CONNECTION_TIMEOUT,
  NetworkError.RESPONSE_TO_LONG,
];
