name: Unit-tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # run on all supported LTS versions and the latest/current version
        node-version: [14, 16, 18, latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.6